package fr.myrilandel.hordemod.registry;

import cpw.mods.fml.common.registry.GameRegistry;
import fr.myrilandel.hordemod.item.ItemTest;
import fr.myrilandel.hordemod.item.Mapper;
import fr.myrilandel.hordemod.item.alcools.CidreClavicepsArtisanal;
import fr.myrilandel.hordemod.item.alcools.DeboutLesMorts;
import fr.myrilandel.hordemod.item.alcools.VodkaMarinostov;
import fr.myrilandel.hordemod.item.armes.AquaSplash;
import fr.myrilandel.hordemod.item.armes.AquaSplashVide;
import fr.myrilandel.hordemod.item.armes.BatteurElectriqueCharge;
import fr.myrilandel.hordemod.item.armes.BatteurElectriqueVide;
import fr.myrilandel.hordemod.item.armes.BombeAEau;
import fr.myrilandel.hordemod.item.armes.BombeAEauExplosive;
import fr.myrilandel.hordemod.item.armes.CanifDerisoire;
import fr.myrilandel.hordemod.item.armes.ChaiseEktorpGluten;
import fr.myrilandel.hordemod.item.armes.CleAMolette;
import fr.myrilandel.hordemod.item.armes.CoupeCoupe;
import fr.myrilandel.hordemod.item.armes.CouteauADents;
import fr.myrilandel.hordemod.item.armes.CouteauSuisse;
import fr.myrilandel.hordemod.item.armes.Cutter;
import fr.myrilandel.hordemod.item.armes.DevastatorCharge;
import fr.myrilandel.hordemod.item.armes.DevastatorVide;
import fr.myrilandel.hordemod.item.armes.FourCancerigene;
import fr.myrilandel.hordemod.item.armes.FusilDAssautVide;
import fr.myrilandel.hordemod.item.armes.GrandBatonSec;
import fr.myrilandel.hordemod.item.armes.GrosseChaineRouillee;
import fr.myrilandel.hordemod.item.armes.LancePile1PDTGCharge;
import fr.myrilandel.hordemod.item.armes.LancePile1PDTGVide;
import fr.myrilandel.hordemod.item.armes.LancePileMarkIICharge;
import fr.myrilandel.hordemod.item.armes.LancePileMarkIIVide;
import fr.myrilandel.hordemod.item.armes.OsHumainFele;
import fr.myrilandel.hordemod.item.armes.OuvreBoites;
import fr.myrilandel.hordemod.item.armes.PamplemousseExplosif;
import fr.myrilandel.hordemod.item.armes.PavesDeBetonInformes;
import fr.myrilandel.hordemod.item.armes.PistoletAEau;
import fr.myrilandel.hordemod.item.armes.PistoletAEauVide;
import fr.myrilandel.hordemod.item.armes.PompeAJerrycanChargee;
import fr.myrilandel.hordemod.item.armes.PompeAJerrycanVide;
import fr.myrilandel.hordemod.item.armes.RefrigerateurDEtudiant;
import fr.myrilandel.hordemod.item.armes.RevolverVide;
import fr.myrilandel.hordemod.item.armes.TaserDAutoDefenseCharge;
import fr.myrilandel.hordemod.item.armes.TaserDAutoDefenseEteint;
import fr.myrilandel.hordemod.item.armes.TelephonePortable;
import fr.myrilandel.hordemod.item.armes.TondeuseAGazon;
import fr.myrilandel.hordemod.item.armes.Torche;
import fr.myrilandel.hordemod.item.armes.TorcheConsumee;
import fr.myrilandel.hordemod.item.armes.Tournevis;
import fr.myrilandel.hordemod.item.armes.TronconneuseChargee;
import fr.myrilandel.hordemod.item.armes.TronconneuseEteinte;
import fr.myrilandel.hordemod.item.armes.UniteCentrale;
import fr.myrilandel.hordemod.item.armes.VieilleMachineALaver;
import fr.myrilandel.hordemod.item.casses.CanifDerisoireCasse;
import fr.myrilandel.hordemod.item.casses.ChaiseEktorpGlutenCassee;
import fr.myrilandel.hordemod.item.casses.CleAMoletteCassee;
import fr.myrilandel.hordemod.item.casses.CoupeCoupeCasse;
import fr.myrilandel.hordemod.item.casses.CouteauADentsCasse;
import fr.myrilandel.hordemod.item.casses.CouteauSuisseCasse;
import fr.myrilandel.hordemod.item.casses.CutterCasse;
import fr.myrilandel.hordemod.item.casses.FourCancerigeneCasse;
import fr.myrilandel.hordemod.item.casses.GrandBatonSecCasse;
import fr.myrilandel.hordemod.item.casses.GrosseChaineRouilleeCassee;
import fr.myrilandel.hordemod.item.casses.GuitareArtisanaleCassee;
import fr.myrilandel.hordemod.item.casses.OsHumainFeleCasse;
import fr.myrilandel.hordemod.item.casses.OuvreBoitesCasse;
import fr.myrilandel.hordemod.item.casses.PavesDeBetonInformesCasses;
import fr.myrilandel.hordemod.item.casses.RefrigerateurDEtudiantCasse;
import fr.myrilandel.hordemod.item.casses.TondeuseAGazonCassee;
import fr.myrilandel.hordemod.item.casses.TorcheConsumeeCassee;
import fr.myrilandel.hordemod.item.casses.TournevisCasse;
import fr.myrilandel.hordemod.item.casses.UniteCentraleCassee;
import fr.myrilandel.hordemod.item.casses.VieilleMachineALaverCassee;
import fr.myrilandel.hordemod.item.coffresFermes.BoiteEnMetal;
import fr.myrilandel.hordemod.item.coffresFermes.CaisseDeMateriel;
import fr.myrilandel.hordemod.item.coffresFermes.CaisseDeNourriture;
import fr.myrilandel.hordemod.item.coffresFermes.CoffreDArchitecteScelle;
import fr.myrilandel.hordemod.item.coffresFermes.CoffreFort;
import fr.myrilandel.hordemod.item.coffresFermes.GrosCoffreFortEnMetal;
import fr.myrilandel.hordemod.item.coffresOuverts.AffaireDUnCitoyen;
import fr.myrilandel.hordemod.item.coffresOuverts.AppareilElectroniqueRepare;
import fr.myrilandel.hordemod.item.coffresOuverts.BoiteDeJeu;
import fr.myrilandel.hordemod.item.coffresOuverts.BoiteDejeuner;
import fr.myrilandel.hordemod.item.coffresOuverts.BoiteEnMetalOuverte;
import fr.myrilandel.hordemod.item.coffresOuverts.CaisseDeMaterielOuverte;
import fr.myrilandel.hordemod.item.coffresOuverts.CaisseDeNourritureOuverte;
import fr.myrilandel.hordemod.item.coffresOuverts.CartonDeMateriaux;
import fr.myrilandel.hordemod.item.coffresOuverts.CoffreDArchitecte;
import fr.myrilandel.hordemod.item.coffresOuverts.CoffreDArchitecteOuvert;
import fr.myrilandel.hordemod.item.coffresOuverts.CoffreFortOuvert;
import fr.myrilandel.hordemod.item.coffresOuverts.ColisPostal;
import fr.myrilandel.hordemod.item.coffresOuverts.DoggyBag;
import fr.myrilandel.hordemod.item.coffresOuverts.EcritAleatoire;
import fr.myrilandel.hordemod.item.coffresOuverts.GrosCoffreFortEnMetalOuvert;
import fr.myrilandel.hordemod.item.coffresOuverts.GrosColisPostal;
import fr.myrilandel.hordemod.item.coffresOuverts.MecanismeDemonte;
import fr.myrilandel.hordemod.item.coffresOuverts.MeubleEnKitAssemble;
import fr.myrilandel.hordemod.item.coffresOuverts.ReserveDUnCitoyenAvise;
import fr.myrilandel.hordemod.item.coffresOuverts.UnColis;
import fr.myrilandel.hordemod.item.coffresOuverts.UneEnveloppe;
import fr.myrilandel.hordemod.item.devEnd.BandageRudimentaire;
import fr.myrilandel.hordemod.item.devEnd.CigaretteAllumee;
import fr.myrilandel.hordemod.item.devEnd.PetitMancheVibrant;
import fr.myrilandel.hordemod.item.drogues.Betapropine5MgPerimee;
import fr.myrilandel.hordemod.item.drogues.Hydratone100Mg;
import fr.myrilandel.hordemod.item.drogues.LSD;
import fr.myrilandel.hordemod.item.drogues.MedicamentSansEtiquette;
import fr.myrilandel.hordemod.item.drogues.PiqureDeCalmant;
import fr.myrilandel.hordemod.item.drogues.SteroidesAnabolisants;
import fr.myrilandel.hordemod.item.drogues.SubstanceAIdentifier;
import fr.myrilandel.hordemod.item.drogues.Twinoides500Mg;
import fr.myrilandel.hordemod.item.eau.BonbonneDEau;
import fr.myrilandel.hordemod.item.eau.EauCroupiePurifiee;
import fr.myrilandel.hordemod.item.eau.RationDEau;
import fr.myrilandel.hordemod.item.inDev.BaliseRadius;
import fr.myrilandel.hordemod.item.inDev.BombeMacabre;
import fr.myrilandel.hordemod.item.inDev.BombePulverine;
import fr.myrilandel.hordemod.item.inDev.Caddie;
import fr.myrilandel.hordemod.item.inDev.CeintureAPoches;
import fr.myrilandel.hordemod.item.inDev.DesherbantNessQuick;
import fr.myrilandel.hordemod.item.inDev.FumigeneSenteurSapin;
import fr.myrilandel.hordemod.item.inDev.FuseeEclairante;
import fr.myrilandel.hordemod.item.inDev.MaglitePif;
import fr.myrilandel.hordemod.item.inDev.Paracetoide7G;
import fr.myrilandel.hordemod.item.inDev.PointeurLaserBrulant;
import fr.myrilandel.hordemod.item.inDev.PointeurLaserBrulantDecharge;
import fr.myrilandel.hordemod.item.inDev.PortiereDeVoiture;
import fr.myrilandel.hordemod.item.inDev.RadiusMarkII;
import fr.myrilandel.hordemod.item.inDev.SacSuperPratique;
import fr.myrilandel.hordemod.item.inDev.SacSupplementaire;
import fr.myrilandel.hordemod.item.inDev.SacocheUsee;
import fr.myrilandel.hordemod.item.inDev.ScieAMetaux;
import fr.myrilandel.hordemod.item.inDev.SportElecCharge;
import fr.myrilandel.hordemod.item.inDev.TeddyNOursMaudit;
import fr.myrilandel.hordemod.item.inDev.Telescope;
import fr.myrilandel.hordemod.item.inDev.Toxine;
import fr.myrilandel.hordemod.item.nourriture.AileronsDePouletEntames;
import fr.myrilandel.hordemod.item.nourriture.BiscuitFades;
import fr.myrilandel.hordemod.item.nourriture.BoiteDeConserveOuverte;
import fr.myrilandel.hordemod.item.nourriture.BonPlatFaitMaison;
import fr.myrilandel.hordemod.item.nourriture.CadavreDUnVoyageur;
import fr.myrilandel.hordemod.item.nourriture.CafeBrulant;
import fr.myrilandel.hordemod.item.nourriture.ChamallowsCalcines;
import fr.myrilandel.hordemod.item.nourriture.ChewingGumsSeches;
import fr.myrilandel.hordemod.item.nourriture.JambonBeurreMoisi;
import fr.myrilandel.hordemod.item.nourriture.LegumeSuspect;
import fr.myrilandel.hordemod.item.nourriture.MelonDIntestin;
import fr.myrilandel.hordemod.item.nourriture.NapolitainsMoisis;
import fr.myrilandel.hordemod.item.nourriture.NouillesChinoises;
import fr.myrilandel.hordemod.item.nourriture.NouillesChinoisesEpicees;
import fr.myrilandel.hordemod.item.nourriture.Oeuf;
import fr.myrilandel.hordemod.item.nourriture.OsCharnu;
import fr.myrilandel.hordemod.item.nourriture.PaquetDeChipsMolles;
import fr.myrilandel.hordemod.item.nourriture.PetitBeurresRances;
import fr.myrilandel.hordemod.item.nourriture.PimsPerime;
import fr.myrilandel.hordemod.item.nourriture.PlatFaitMaisonDouteux;
import fr.myrilandel.hordemod.item.nourriture.PoigneeDeBonbons;
import fr.myrilandel.hordemod.item.nourriture.Pomme;
import fr.myrilandel.hordemod.item.nourriture.PureeDeCharognardes;
import fr.myrilandel.hordemod.item.nourriture.SteakAppetissant;
import fr.myrilandel.hordemod.item.nourriture.SteakDeSciure;
import fr.myrilandel.hordemod.item.nourriture.ViandeHumaine;
import fr.myrilandel.hordemod.item.nourriture.ViandeIndefinissable;
import fr.myrilandel.hordemod.item.objJournaliers.Des;
import fr.myrilandel.hordemod.item.objJournaliers.GuitareArtisanale;
import fr.myrilandel.hordemod.item.objJournaliers.JeuDeCartes;
import fr.myrilandel.hordemod.item.objJournaliers.TeddyNOurs;
import fr.myrilandel.hordemod.item.plans.PlanCommun;
import fr.myrilandel.hordemod.item.plans.PlanCommunHopital;
import fr.myrilandel.hordemod.item.plans.PlanInhabituel;
import fr.myrilandel.hordemod.item.plans.PlanInhabituelBunker;
import fr.myrilandel.hordemod.item.plans.PlanInhabituelHopital;
import fr.myrilandel.hordemod.item.plans.PlanInhabituelHotel;
import fr.myrilandel.hordemod.item.plans.PlanRare;
import fr.myrilandel.hordemod.item.plans.PlanRareBunker;
import fr.myrilandel.hordemod.item.plans.PlanRareHopital;
import fr.myrilandel.hordemod.item.plans.PlanRareHotel;
import fr.myrilandel.hordemod.item.plans.PlanTresRare;
import fr.myrilandel.hordemod.item.plans.PlanTresRareBunker;
import fr.myrilandel.hordemod.item.plans.PlanTresRareHopital;
import fr.myrilandel.hordemod.item.plans.PlanTresRareHotel;
import fr.myrilandel.hordemod.item.points.PointDAtelier;
import fr.myrilandel.hordemod.item.points.PointDeChantier;
import fr.myrilandel.hordemod.item.poisons.BoiteDeConserveOuvertePoison;
import fr.myrilandel.hordemod.item.poisons.Cyanure;
import fr.myrilandel.hordemod.item.poisons.FioleDePoison;
import fr.myrilandel.hordemod.item.poisons.LegumeSuspectPoison;
import fr.myrilandel.hordemod.item.poisons.PureeDeCharognardesPoison;
import fr.myrilandel.hordemod.item.poisons.RationDEauPoison;
import fr.myrilandel.hordemod.item.poisons.SteroidesAnabolisantsPoison;
import fr.myrilandel.hordemod.item.ressources.*;
import fr.myrilandel.hordemod.item.rp.AlbumPhoto;
import fr.myrilandel.hordemod.item.rp.CarnetIllisible;
import fr.myrilandel.hordemod.item.rp.FeuilleRaccornie;
import fr.myrilandel.hordemod.item.rp.LivrePoussiereux;
import fr.myrilandel.hordemod.item.rp.LivreZenMiniature;
import fr.myrilandel.hordemod.item.rp.ManuelDInstructions;
import fr.myrilandel.hordemod.item.rp.NoteDUnCitoyenBanni;
import fr.myrilandel.hordemod.item.rp.PileDeFeuille;
import fr.myrilandel.hordemod.item.rp.UneEncyclopedie;
import fr.myrilandel.hordemod.item.rp.UneEtiquette;
import fr.myrilandel.hordemod.item.rp.UneLettreSansAdresse;
import net.minecraft.item.Item;
	
public class HMItemRegistry {
	
	public static Item itemTest = new ItemTest();
	public static Item mapper = new Mapper();
	
	public static Item aileronsDePouletEntames = new AileronsDePouletEntames();
	public static Item albumPhoto = new AlbumPhoto();
	public static Item appareilElectroniqueEnPanne = new AppareilElectroniqueEnPanne();
	public static Item aquaSplash = new AquaSplash();	
	public static Item aquaSplashDemonte = new AquaSplashDemonte();	
	public static Item aquaSplashVide = new AquaSplashVide();	
	public static Item badgeDeSherif = new BadgeDeSherif();
	public static Item baliseRadius = new BaliseRadius();
	public static Item bandageRudimentaire = new BandageRudimentaire();
	public static Item barricadeAClouer = new BarricadeAClouer();
	public static Item batteurElectriqueCharge = new BatteurElectriqueCharge();
	public static Item batteurElectriqueVide = new BatteurElectriqueVide();
	public static Item batteurElectriqueIncomplet = new BatteurElectriqueIncomplet();
	public static Item betapropine5MgPerimee = new Betapropine5MgPerimee();
	public static Item bidonDHuileVide = new BidonDHuileVide();
	public static Item biscuitFades = new BiscuitFades();
	public static Item bobineDeFilDeFer = new BobineDeFilDeFer();
	public static Item boiteDAllumettes = new BoiteDAllumettes();
	public static Item boiteEnMetal = new BoiteEnMetal();
	public static Item boiteDeConserve = new BoiteDeConserve();
	public static Item boiteDeConserveOuverte = new BoiteDeConserveOuverte();
	public static Item boiteDeConserveOuvertePoison = new BoiteDeConserveOuvertePoison();
	public static Item bonPlatFaitMaison = new BonPlatFaitMaison();
	public static Item bombeAEau = new BombeAEau();
	public static Item bombeAEauExplosive = new BombeAEauExplosive();
	public static Item bombeMacabre = new BombeMacabre();
	public static Item bombePulverine = new BombePulverine();
	public static Item bonbonneDEau = new BonbonneDEau();
	public static Item bonbonneDEauVide = new BonbonneDEauVide();
	public static Item bouleDePateVisqueuse = new BouleDePateVisqueuse();
	public static Item bouleQuies = new BouleQuies();
	public static Item bricoFacile = new BricoFacile();
	public static Item bucheEnBonEtat = new BucheEnBonEtat();
	public static Item bureauMonteALaRache = new BureauMonteALaRache();
	public static Item cadavreDUnVoyageur = new CadavreDUnVoyageur();
	public static Item cadavreRonge = new CadavreRonge();
	public static Item caddie = new Caddie();
	public static Item caddieBancal = new CaddieBancal();
	public static Item cafeBrulant = new CafeBrulant();
	public static Item cafetiere = new Cafetiere();
	public static Item cafetiereIncomplete = new CafetiereIncomplete();
	public static Item caisseDeFeuxDArtifice = new CaisseDeFeuxDArtifice();
	public static Item caisseDeMateriel = new CaisseDeMateriel();
	public static Item caisseDeNourriture = new CaisseDeNourriture();
	public static Item calibrateurPDTTMarkII = new CalibrateurPDTTMarkII();
	public static Item canifDerisoire = new CanifDerisoire();
	public static Item canifDerisoireCasse = new CanifDerisoireCasse();
	public static Item cantineDeFer = new CantineDeFer();
	public static Item carnetIllisible = new CarnetIllisible();
	public static Item cartons = new Cartons();
	public static Item CDBritneySpears = new CDBritneySpears();
	public static Item CDPhilCollins = new CDPhilCollins();
	public static Item ceintureAPoches = new CeintureAPoches();
	public static Item chaineDePorteEtCadenas = new ChaineDePorteEtCadenas();
	public static Item chaineHiFiDefensive = new ChaineHiFiDefensive();
	public static Item chaineHiFiMaudite = new ChaineHiFiMaudite();
	public static Item chaineHiFiRockNRoll = new ChaineHiFiRockNRoll();
	public static Item chaiseEktorpGluten = new ChaiseEktorpGluten();
	public static Item chaiseEktorpGlutenCassee = new ChaiseEktorpGlutenCassee();
	public static Item chamallowsCalcines = new ChamallowsCalcines();
	public static Item chamallowsSeches = new ChamallowsSeches();
	public static Item charognardes = new Charognardes();
	public static Item chewingGumsSeches = new ChewingGumsSeches();
	public static Item cidreClavicepsArtisanal = new CidreClavicepsArtisanal();
	public static Item cigaretteAllumee = new CigaretteAllumee();
	public static Item clavicepsPurpurea = new ClavicepsPurpurea();
	public static Item cleAMolette = new CleAMolette();
	public static Item cleAMoletteCassee = new CleAMoletteCassee();
	public static Item coffreDArchitecteScelle = new CoffreDArchitecteScelle();
	public static Item coffreFort = new CoffreFort();
	public static Item compilationDuKing = new CompilationDuKing();
	public static Item composantElectronique = new ComposantElectronique();
	public static Item coupeCoupe = new CoupeCoupe();
	public static Item coupeCoupeCasse = new CoupeCoupeCasse();
	public static Item courroie = new Courroie();
	public static Item couteauADents = new CouteauADents();
	public static Item couteauADentsCasse = new CouteauADentsCasse();
	public static Item couteauSuisse = new CouteauSuisse();
	public static Item couteauSuisseCasse = new CouteauSuisseCasse();
	public static Item cutter = new Cutter();
	public static Item cutterCasse = new CutterCasse();
	public static Item cyanure = new Cyanure();
	public static Item deboutLesMorts = new DeboutLesMorts();
	public static Item debrisMeconnaissables = new DebrisMeconnaissables();	
	public static Item debrisMetalliques = new DebrisMetalliques();
	public static Item des = new Des();	
	public static Item desherbantNessQuick = new DesherbantNessQuick();	
	public static Item detonateurCompact = new DetonateurCompact();	
	public static Item devastatorCharge = new DevastatorCharge();
	public static Item devastatorIncomplet = new DevastatorIncomplet();
	public static Item devastatorVide = new DevastatorVide();
	public static Item diodeLazer = new DiodeLazer();	
	public static Item discoursRassurantMulticolore = new DiscoursRassurantMulticolore();	
	public static Item distributeurVide = new DistributeurVide();	
	public static Item eauCroupie = new EauCroupie();
	public static Item eauCroupiePurifiee = new EauCroupiePurifiee();
	public static Item epicesFortes = new EpicesFortes();
	public static Item explosifsBruts = new ExplosifsBruts();
	public static Item ferraille = new Ferraille();
    public static Item feuilleRaccornie = new FeuilleRaccornie(); 
    public static Item figurineDeChuck = new FigurineDeChuck(); 
    public static Item fioleDePoison = new FioleDePoison(); 
	public static Item fourCancerigene = new FourCancerigene();
    public static Item fourCancerigeneCasse = new FourCancerigeneCasse(); 
    public static Item fragmentsDeTole = new FragmentsDeTole(); 
    public static Item fumigeneSenteurSapin = new FumigeneSenteurSapin(); 
    public static Item fusilDAssautVide = new FusilDAssautVide(); 
    public static Item fuseeEclairante = new FuseeEclairante(); 
	public static Item grandBatonSec = new GrandBatonSec();
	public static Item grandBatonSecCasse = new GrandBatonSecCasse();
    public static Item grosCoffreFortEnMetal = new GrosCoffreFortEnMetal();
	public static Item grosseChaineRouillee = new GrosseChaineRouillee();
	public static Item grosseChaineRouilleeCassee = new GrosseChaineRouilleeCassee();
	public static Item guitareArtisanale = new GuitareArtisanale();
	public static Item guitareArtisanaleCassee = new GuitareArtisanaleCassee();
	public static Item hydratone100Mg = new Hydratone100Mg();
	public static Item jambonBeurreMoisi = new JambonBeurreMoisi();
	public static Item jeuDeCartes = new JeuDeCartes();
	public static Item jerrycanPlein = new JerrycanPlein();
	public static Item kitDeBricolage = new KitDeBricolage();
	public static Item kitDeBricolageAbime = new KitDeBricolageAbime();
	public static Item lambeauDeChair = new LambeauDeChair();
	public static Item lampeDeChevetAllumee = new LampeDeChevetAllumee();
	public static Item lampeDeChevetEteinte = new LampeDeChevetEteinte();
	public static Item lancePieu = new LancePieu();
	public static Item lancePileMarkIICharge = new LancePileMarkIICharge();
	public static Item lancePileMarkIIVide = new LancePileMarkIIVide();
	public static Item lancePile1PDTGCharge = new LancePile1PDTGCharge();
	public static Item lancePile1PDTGVide = new LancePile1PDTGVide();
	public static Item legumeSuspect = new LegumeSuspect();
	public static Item legumeSuspectPoison = new LegumeSuspectPoison();
	public static Item lentilleConvexe = new LentilleConvexe();
	public static Item liasseDeBillets = new LiasseDeBillets();
	public static Item livrePoussiereux = new LivrePoussiereux();
	public static Item livreZenMiniature = new LivreZenMiniature();
	public static Item LSD = new LSD();
	public static Item maglitePif = new MaglitePif();
	public static Item maglitePifEteint = new MaglitePifEteint();
	public static Item manuelDInstructions = new ManuelDInstructions();
	public static Item matelas = new Matelas();
	public static Item mecanisme = new Mecanisme();
	public static Item medicamentSansEtiquette = new MedicamentSansEtiquette();
	public static Item melonDIntestin = new MelonDIntestin();
	public static Item meubleEnKit = new MeubleEnKit();
	public static Item micropurEffervescent = new MicropurEffervescent();
	public static Item mineAntiPersonnel = new MineAntiPersonnel();
	public static Item morceauDeCaisse = new MorceauDeCaisse();
	public static Item morceauDeContreplaque = new MorceauDeContreplaque();
	public static Item morceauDeGrillage = new MorceauDeGrillage();
	public static Item moteur = new Moteur();
	public static Item moteurIncomplet = new MoteurIncomplet();
	public static Item napolitainsMoisis = new NapolitainsMoisis();
	public static Item noteDUnCitoyenBanni = new NoteDUnCitoyenBanni();
	public static Item nouillesChinoises = new NouillesChinoises();
	public static Item nouillesChinoisesEpicees = new NouillesChinoisesEpicees();
	public static Item oeuf = new Oeuf();
	public static Item osCharnu = new OsCharnu();
	public static Item osHumainFele = new OsHumainFele();
	public static Item osHumainFeleCasse = new OsHumainFeleCasse();
	public static Item outilsEnVrac = new OutilsEnVrac();
	public static Item ouvreBoites = new OuvreBoites();
	public static Item ouvreBoitesCasse = new OuvreBoitesCasse();
	public static Item paillasson = new Paillasson();
	public static Item paillassonPiege = new PaillassonPiege();
	public static Item pamplemousseExplosif = new PamplemousseExplosif();
	public static Item paquetDeChipsMolles = new PaquetDeChipsMolles();
	public static Item paquetDeCigarettesEntame = new PaquetDeCigarettesEntame();
	public static Item paracetoide7G = new Paracetoide7G();	
	public static Item pavesDeBetonInformes = new PavesDeBetonInformes();
	public static Item pavesDeBetonInformesCasses = new PavesDeBetonInformesCasses();
	public static Item peluresDePeau = new PeluresDePeau();
	public static Item petitBeurresRances = new PetitBeurresRances();
	public static Item petitMancheVibrant = new PetitMancheVibrant();
	public static Item petitMancheVibrantEteint = new PetitMancheVibrantEteint();
	public static Item petiteChaineHiFi = new PetiteChaineHiFi();
	public static Item petiteChaineHiFiEnPanne = new PetiteChaineHiFiEnPanne();
	public static Item pile = new Pile();
	public static Item pileBroyee = new PileBroyee();
	public static Item pileDeFeuille= new PileDeFeuille();
	public static Item pimsPerime = new PimsPerime();
	public static Item piqureDeCalmant = new PiqureDeCalmant();
	public static Item pistoletAEau = new PistoletAEau();
	public static Item pistoletAEauVide = new PistoletAEauVide();
	public static Item planchesTordue = new PlanchesTordue();
	public static Item plaqueDeBoisSolide = new PlaqueDeBoisSolide();
	public static Item plaqueDeTole = new PlaqueDeTole();
	public static Item platFaitMaisonDouteux = new PlatFaitMaisonDouteux();
	public static Item poigneeDeBonbons = new PoigneeDeBonbons();
	public static Item poigneeDeVisEtEcrous = new PoigneeDeVisEtEcrous();
	public static Item pointDAtelier = new PointDAtelier();
	public static Item pointDeChantier = new PointDeChantier();
	public static Item pointeurLaserBrulant = new PointeurLaserBrulant();
	public static Item pointeurLaserBrulantDecharge = new PointeurLaserBrulantDecharge();
	public static Item pomme = new Pomme();
	public static Item pompeAJerrycanChargee = new PompeAJerrycanChargee();
	public static Item pompeAJerrycanDemontee = new PompeAJerrycanDemontee();
	public static Item pompeAJerrycanVide = new PompeAJerrycanVide();
	public static Item portiereDeVoiture = new PortiereDeVoiture();
	public static Item portiereDeVoitureIncomplete = new PortiereDeVoitureIncomplete();
	public static Item poudreCometeBrute = new PoudreCometeBrute();
	public static Item poudreSuperFuzz = new PoudreSuperFuzz();
	public static Item poutreRafistolee = new PoutreRafistolee();
	public static Item produitCorrosif = new ProduitCorrosif();
	public static Item produitsPharmaceutiques = new ProduitsPharmaceutiques();
	public static Item pureeDeCharognardes = new PureeDeCharognardes();
	public static Item pureeDeCharognardesPoison = new PureeDeCharognardesPoison();
	public static Item radioK7 = new RadioK7();
	public static Item radioK7Eteint = new RadioK7Eteint();
	public static Item radiusMarkII = new RadiusMarkII();
	public static Item radiusMarkIIDechargee = new RadiusMarkIIDechargee();
	public static Item rationDEau = new RationDEau();
	public static Item rationDEauPoison = new RationDEauPoison();
	public static Item refrigerateurDEtudiant = new RefrigerateurDEtudiant();
	public static Item refrigerateurDEtudiantCasse = new RefrigerateurDEtudiantCasse();
	public static Item revolverVide = new RevolverVide();
	public static Item rockingChair = new RockingChair();
	public static Item rustine = new Rustine();
	public static Item sacDeCiment = new SacDeCiment();
	public static Item sacPlastique = new SacPlastique();
	public static Item sacPlastiqueExplosif = new SacPlastiqueExplosif();
	public static Item sacSuperPratique = new SacSuperPratique();
	public static Item sacSupplementaire = new SacSupplementaire();
	public static Item sachetDHerbeFraiche = new SachetDHerbeFraiche();
	public static Item scieAMetaux = new ScieAMetaux();
	public static Item scieAMetauxAbimee = new ScieAMetauxAbimee();
	public static Item sportElecCharge = new SportElecCharge();
	public static Item sportElecEteint = new SportElecEteint();
	public static Item steakDeSciure = new SteakDeSciure();
	public static Item soucheDeBoisPourrie = new SoucheDeBoisPourrie();
	public static Item steakAppetissant = new SteakAppetissant();
	public static Item steroidesAnabolisants = new SteroidesAnabolisants();
	public static Item steroidesAnabolisantsPoison = new SteroidesAnabolisantsPoison();
	public static Item structuresMetalliques = new StructuresMetalliques();
	public static Item substanceEpaisse = new SubstanceEpaisse();
	public static Item tableJarpen = new TableJarpen();
	public static Item tapisPersan = new TapisPersan();
	public static Item taserDAutoDefenseCharge = new TaserDAutoDefenseCharge();
	public static Item taserDAutoDefenseEteint = new TaserDAutoDefenseEteint();
	public static Item teddyNOurs = new TeddyNOurs();
	public static Item teddyNOursMaudit = new TeddyNOursMaudit();
	public static Item telephonePortable = new TelephonePortable();
	public static Item telescope = new Telescope();
	public static Item toileDeTente = new ToileDeTente();
	public static Item tondeuseAGazon = new TondeuseAGazon();
	public static Item tondeuseAGazonCassee = new TondeuseAGazonCassee();
	public static Item tondeuseAGazonDemontee = new TondeuseAGazonDemontee();
	public static Item torche = new Torche();
	public static Item torcheConsumee = new TorcheConsumee();
	public static Item torcheConsumeeCassee = new TorcheConsumeeCassee();
	public static Item tournevis = new Tournevis();
	public static Item tournevisCasse = new TournevisCasse();
	public static Item treteau = new Treteau();	
	public static Item toxine = new Toxine();
	public static Item tronconneuseChargee = new TronconneuseChargee();
	public static Item tronconneuseEteinte = new TronconneuseEteinte();
	public static Item tronconneuseIncomplete = new TronconneuseIncomplete();
	public static Item tubeDeCuivre = new TubeDeCuivre();
	public static Item tubeDeLancementFloush = new TubeDeLancementFloush();
	public static Item twinoides500Mg = new Twinoides500Mg();
	public static Item uneEncyclopedie = new UneEncyclopedie();
	public static Item uneEtiquette = new UneEtiquette();
	public static Item uneLettreSansAdresse = new UneLettreSansAdresse();
	public static Item uniteCentrale = new UniteCentrale();
	public static Item uniteCentraleCassee = new UniteCentraleCassee();
	public static Item viandeHumaine = new ViandeHumaine();
	public static Item viandeIndefinissable = new ViandeIndefinissable();
	public static Item vieilleMachineALaver = new VieilleMachineALaver();
	public static Item vieilleMachineALaverCassee = new VieilleMachineALaverCassee();
	public static Item vieillePorte = new VieillePorte();
	public static Item vodkaMarinostov = new VodkaMarinostov();
	
	public static Item affaireDUnCitoyen = new AffaireDUnCitoyen();
	public static Item appareilElectroniqueRepare = new AppareilElectroniqueRepare();
	public static Item boiteDeJeu = new BoiteDeJeu();
	public static Item boiteDejeuner = new BoiteDejeuner();
	//public static Item boiteDeSchrodinger = new BoiteDeSchrodinger();
	public static Item boiteEnMetalOuverte = new BoiteEnMetalOuverte();
	public static Item caisseDeMaterielOuverte = new CaisseDeMaterielOuverte();
	public static Item cartonDeMateriaux = new CartonDeMateriaux();
	public static Item coffreDArchitecte = new CoffreDArchitecte();
	public static Item coffreDArchitecteOuvert = new CoffreDArchitecteOuvert();
	public static Item doggyBag = new DoggyBag();
	public static Item ecritAleatoire = new EcritAleatoire();
	public static Item grosCoffreFortEnMetalOuvert = new GrosCoffreFortEnMetalOuvert();
	public static Item mecanismeDemonte = new MecanismeDemonte();
	public static Item meubleEnKitAssemble = new MeubleEnKitAssemble();
	public static Item reserveDUnCitoyenAvise = new ReserveDUnCitoyenAvise();
	public static Item sacocheUsee = new SacocheUsee();
	public static Item substanceAIdentifier = new SubstanceAIdentifier();
	public static Item uneEnveloppe = new UneEnveloppe();
	
	public static Item caisseDeNourritureOuverte = new CaisseDeNourritureOuverte();
	public static Item coffreFortOuvert = new CoffreFortOuvert();
	public static Item colisPostal = new ColisPostal();
	public static Item grosColisPostal = new GrosColisPostal();
	public static Item unColis = new UnColis();
	
	public static Item planCommun = new PlanCommun();
	public static Item planCommunHopital = new PlanCommunHopital();
	public static Item planInhabituel = new PlanInhabituel();
	public static Item planInhabituelBunker = new PlanInhabituelBunker();
	public static Item planInhabituelHopital = new PlanInhabituelHopital();
	public static Item planInhabituelHotel = new PlanInhabituelHotel();
	public static Item planRare = new PlanRare();
	public static Item planRareBunker = new PlanRareBunker();
	public static Item planRareHopital = new PlanRareHopital();
	public static Item planRareHotel = new PlanRareHotel();
	public static Item planTresRare = new PlanTresRare();
	public static Item planTresRareBunker = new PlanTresRareBunker();
	public static Item planTresRareHopital = new PlanTresRareHopital();
	public static Item planTresRareHotel = new PlanTresRareHotel();

	public static void itemRegister() {
		GameRegistry.registerItem(mapper, "mapper");
		
		GameRegistry.registerItem(aileronsDePouletEntames, "aileronsDePouletEntames");
		GameRegistry.registerItem(albumPhoto, "albumPhoto");
		GameRegistry.registerItem(appareilElectroniqueEnPanne, "appareilElectroniqueEnPanne");
		GameRegistry.registerItem(aquaSplash,"aquaSplash");
		GameRegistry.registerItem(aquaSplashDemonte, "aquaSplashDemonte");
		GameRegistry.registerItem(aquaSplashVide,"aquaSplashVide");
		GameRegistry.registerItem(badgeDeSherif, "badgeDeSherif");
		GameRegistry.registerItem(baliseRadius, "baliseRadius");
		GameRegistry.registerItem(bandageRudimentaire, "bandageRudimentaire");
		GameRegistry.registerItem(barricadeAClouer, "barricadeAClouer");
		GameRegistry.registerItem(batteurElectriqueVide, "batteurElectriqueVide");
		GameRegistry.registerItem(batteurElectriqueCharge, "batteurElectriqueCharge");
		GameRegistry.registerItem(batteurElectriqueIncomplet, "batteurElectriqueIncomplet");
		GameRegistry.registerItem(bidonDHuileVide,"bidonDHuileVide");
		GameRegistry.registerItem(betapropine5MgPerimee,"betapropine5MgPerimee");
		GameRegistry.registerItem(biscuitFades, "biscuitFades");
		GameRegistry.registerItem(bobineDeFilDeFer,"bobineDeFilDeFer");
		GameRegistry.registerItem(boiteDAllumettes, "boiteDAllumettes");
		GameRegistry.registerItem(boiteEnMetal, "boiteEnMetal");
		GameRegistry.registerItem(boiteDeConserve, "boiteDeConserve");
		GameRegistry.registerItem(boiteDeConserveOuverte, "boiteDeConserveOuverte");
		GameRegistry.registerItem(boiteDeConserveOuvertePoison, "boiteDeConserveOuvertePoison");
		GameRegistry.registerItem(bombeAEau, "bombeAEau");
		GameRegistry.registerItem(bombeAEauExplosive, "bombeAEauExplosive");
		GameRegistry.registerItem(bombeMacabre, "bombeMacabre");
		GameRegistry.registerItem(bombePulverine, "bombePulverine");
		GameRegistry.registerItem(bonbonneDEau, "bonbonneDEau");
		GameRegistry.registerItem(bonbonneDEauVide, "bonbonneDEauVide");
		GameRegistry.registerItem(bonPlatFaitMaison, "bonPlatFaitMaison");
		GameRegistry.registerItem(bouleDePateVisqueuse, "bouleDePateVisqueuse");
		GameRegistry.registerItem(bouleQuies, "bouleQuies");
		GameRegistry.registerItem(bricoFacile, "bricoFacile	");
		GameRegistry.registerItem(bucheEnBonEtat, "bucheEnBonEtat");
		GameRegistry.registerItem(bureauMonteALaRache, "bureauMonteALaRache");
		GameRegistry.registerItem(cadavreDUnVoyageur, "cadavreDUnVoyageur");
		GameRegistry.registerItem(cadavreRonge, "cadavreRonge");
		GameRegistry.registerItem(caddie, "caddie");
		GameRegistry.registerItem(caddieBancal, "caddieBancal");
		GameRegistry.registerItem(cafeBrulant, "cafeBrulant");
		GameRegistry.registerItem(cafetiere, "cafetiere");
		GameRegistry.registerItem(cafetiereIncomplete, "cafetiereIncomplete");
		GameRegistry.registerItem(caisseDeFeuxDArtifice, "caisseDeFeuxDArtifice");
		GameRegistry.registerItem(caisseDeMateriel, "caisseDeMateriel");
		GameRegistry.registerItem(caisseDeNourriture, "caisseDeNourriture");
		GameRegistry.registerItem(calibrateurPDTTMarkII, "calibrateurPDTTMarkII");
		GameRegistry.registerItem(canifDerisoire, "canifDerisoire");
		GameRegistry.registerItem(canifDerisoireCasse, "canifDerisoireCasse");
		GameRegistry.registerItem(cantineDeFer, "cantineDeFer");
		GameRegistry.registerItem(carnetIllisible, "carnetIllisible");
		GameRegistry.registerItem(cartons, "cartons");
		GameRegistry.registerItem(CDBritneySpears, "CDBritneySpears");
		GameRegistry.registerItem(CDPhilCollins, "CDPhilCollins");
		GameRegistry.registerItem(ceintureAPoches, "ceintureAPoches");
		GameRegistry.registerItem(chaineDePorteEtCadenas, "chaineDePorteEtCadenas");
		GameRegistry.registerItem(chaineHiFiDefensive,"chaineHiFiDefensive");
		GameRegistry.registerItem(chaineHiFiMaudite,"chaineHiFiMaudite");
		GameRegistry.registerItem(chaineHiFiRockNRoll,"chaineHiFiRockNRoll");
		GameRegistry.registerItem(chaiseEktorpGluten,"chaiseEktorpGluten");
		GameRegistry.registerItem(chaiseEktorpGlutenCassee,"chaiseEktorpGlutenCassee");
		GameRegistry.registerItem(chamallowsCalcines, "chamallowsCalcines");
		GameRegistry.registerItem(chamallowsSeches, "chamallowsSeches");
		GameRegistry.registerItem(charognardes, "charognardes");
		GameRegistry.registerItem(chewingGumsSeches, "chewingGumsSeches");
		GameRegistry.registerItem(cidreClavicepsArtisanal, "cidreClavicepsArtisanal");
		GameRegistry.registerItem(cigaretteAllumee, "cigaretteAllumee");
		GameRegistry.registerItem(clavicepsPurpurea, "clavicepsPurpurea");
		GameRegistry.registerItem(cleAMolette, "cleAMolette");
		GameRegistry.registerItem(cleAMoletteCassee, "cleAMoletteCassee");
		GameRegistry.registerItem(coffreDArchitecteScelle, "coffreDArchitecteScelle");
		GameRegistry.registerItem(coffreFort, "coffreFort");
		GameRegistry.registerItem(compilationDuKing,"compilationDuKing");
		GameRegistry.registerItem(composantElectronique,"composantElectronique");
		GameRegistry.registerItem(coupeCoupe, "coupeCoupe");
		GameRegistry.registerItem(coupeCoupeCasse, "coupeCoupeCasse");
		GameRegistry.registerItem(courroie,"courroie");
		GameRegistry.registerItem(couteauADents,"couteauADents");
		GameRegistry.registerItem(couteauADentsCasse,"couteauADentsCasse");
		GameRegistry.registerItem(couteauSuisse,"couteauSuisse");
		GameRegistry.registerItem(couteauSuisseCasse,"couteauSuisseCasse");
		GameRegistry.registerItem(cutter,"cutter");
		GameRegistry.registerItem(cutterCasse,"cutterCasse");
		GameRegistry.registerItem(cyanure, "cyanure");
		GameRegistry.registerItem(deboutLesMorts, "deboutLesMorts");
		GameRegistry.registerItem(debrisMeconnaissables,"debrisMeconnaissables");
		GameRegistry.registerItem(debrisMetalliques,"debrisMetalliques");
		GameRegistry.registerItem(desherbantNessQuick, "desherbantNessQuick");
		GameRegistry.registerItem(des, "des");
		GameRegistry.registerItem(detonateurCompact,"detonateurCompact");
		GameRegistry.registerItem(devastatorCharge, "devastatorCharge");
		GameRegistry.registerItem(devastatorIncomplet, "devastatorIncomplet");
		GameRegistry.registerItem(devastatorVide, "devastatorVide");
		//GameRegistry.registerItem(diodeLazer,"diodeLazer");
		GameRegistry.registerItem(discoursRassurantMulticolore,"discoursRassurantMulticolore");
		GameRegistry.registerItem(distributeurVide,"distributeurVide");
		GameRegistry.registerItem(eauCroupie, "eauCroupie");
		GameRegistry.registerItem(eauCroupiePurifiee, "eauCroupiePurifiee");
		GameRegistry.registerItem(epicesFortes, "epicesFortes");
		GameRegistry.registerItem(explosifsBruts, "explosifsBruts");
		GameRegistry.registerItem(ferraille, "ferraille");
		GameRegistry.registerItem(feuilleRaccornie, "feuilleRaccornie");
		GameRegistry.registerItem(figurineDeChuck, "figurineDeChuck");
		GameRegistry.registerItem(fioleDePoison, "fioleDePoison");
		GameRegistry.registerItem(fourCancerigene, "fourCancerigenee");
		GameRegistry.registerItem(fourCancerigeneCasse, "fourCancerigeneCasse");
		GameRegistry.registerItem(fragmentsDeTole,"fragmentsDeTole");
		GameRegistry.registerItem(fumigeneSenteurSapin,"fumigeneSenteurSapin");
		GameRegistry.registerItem(fusilDAssautVide,"fusilDAssautVide");
		GameRegistry.registerItem(fuseeEclairante,"fuseeEclairante");
		GameRegistry.registerItem(grandBatonSec, "grandBatonSec");
		GameRegistry.registerItem(grandBatonSecCasse, "grandBatonSecCasse");
		GameRegistry.registerItem(grosCoffreFortEnMetal, "grosCoffreFortEnMetal");
		GameRegistry.registerItem(grosseChaineRouillee, "grosseChaineRouillee");
		GameRegistry.registerItem(grosseChaineRouilleeCassee, "grosseChaineRouilleeCassee");
		GameRegistry.registerItem(guitareArtisanale, "guitareArtisanale");
		GameRegistry.registerItem(guitareArtisanaleCassee, "guitareArtisanaleCassee");
		GameRegistry.registerItem(hydratone100Mg, "hydratone100Mg");
		GameRegistry.registerItem(jambonBeurreMoisi, "jambonBeurreMoisi");
		GameRegistry.registerItem(jeuDeCartes, "jeuDeCartes");
		GameRegistry.registerItem(jerrycanPlein, "jerrycanPlein");
		GameRegistry.registerItem(kitDeBricolage, "kitDeBricolage");
		GameRegistry.registerItem(kitDeBricolageAbime, "kitDeBricolageAbime");
		GameRegistry.registerItem(lancePieu, "lancePieu");
		GameRegistry.registerItem(lancePileMarkIICharge, "lancePileMarkIICharge");
		GameRegistry.registerItem(lancePileMarkIIVide, "lancePileMarkIIVide");
		GameRegistry.registerItem(lancePile1PDTGCharge, "lancePile1PDTGCharge");
		GameRegistry.registerItem(lancePile1PDTGVide, "lancePile1PDTGVide");
		GameRegistry.registerItem(lambeauDeChair, "lambeauDeChair");
		GameRegistry.registerItem(lampeDeChevetAllumee, "lampeDeChevetAllumee");
		GameRegistry.registerItem(lampeDeChevetEteinte, "lampeDeChevetEteinte");
		GameRegistry.registerItem(legumeSuspect, "legumeSuspect");
		GameRegistry.registerItem(legumeSuspectPoison, "legumeSuspectPoison");
		GameRegistry.registerItem(lentilleConvexe,"lentilleConvexe");
		GameRegistry.registerItem(liasseDeBillets,"liasseDeBillets");
		GameRegistry.registerItem(livrePoussiereux, "livrePoussiereux");
		GameRegistry.registerItem(livreZenMiniature, "livreZenMiniature");
		GameRegistry.registerItem(LSD,"LSD");
		//GameRegistry.registerItem(maglitePif, "maglitePif");
		//GameRegistry.registerItem(maglitePifEteint, "maglitePifEteint");
		GameRegistry.registerItem(manuelDInstructions, "manuelDInstructions");
		GameRegistry.registerItem(matelas, "matelas");
		GameRegistry.registerItem(mecanisme, "mecanisme");
		GameRegistry.registerItem(medicamentSansEtiquette,"medicamentSansEtiquette");
		GameRegistry.registerItem(melonDIntestin, "melonDIntestin");
		GameRegistry.registerItem(meubleEnKit, "meubleEnKit");
		GameRegistry.registerItem(micropurEffervescent,"micropurEffervescent");
		GameRegistry.registerItem(mineAntiPersonnel,"mineAntiPersonnel");
		GameRegistry.registerItem(morceauDeCaisse,"morceauDeCaisse");
		GameRegistry.registerItem(morceauDeContreplaque,"morceauDeContreplaque");
		GameRegistry.registerItem(morceauDeGrillage,"morceauDeGrillage");
		GameRegistry.registerItem(moteur,"moteur");
		GameRegistry.registerItem(moteurIncomplet,"moteurIncomplet");
		GameRegistry.registerItem(napolitainsMoisis, "napolitainsMoisis");
		GameRegistry.registerItem(noteDUnCitoyenBanni, "noteDUnCitoyenBanni");
		GameRegistry.registerItem(nouillesChinoises, "nouillesChinoises");
		GameRegistry.registerItem(nouillesChinoisesEpicees, "nouillesChinoisesEpicees");
		GameRegistry.registerItem(oeuf, "oeuf");
		GameRegistry.registerItem(osCharnu, "osCharnu");
		GameRegistry.registerItem(osHumainFele, "osHumainFele");
		GameRegistry.registerItem(osHumainFeleCasse, "osHumainFeleCasse");
		GameRegistry.registerItem(outilsEnVrac, "outilsEnVrac");
		GameRegistry.registerItem(ouvreBoites, "ouvreBoites");
		GameRegistry.registerItem(ouvreBoitesCasse, "ouvreBoitesCasse");
		GameRegistry.registerItem(paillasson, "paillasson");
		GameRegistry.registerItem(paillassonPiege, "paillassonPiege");
		GameRegistry.registerItem(pamplemousseExplosif, "pamplemousseExplosif");
		GameRegistry.registerItem(paquetDeChipsMolles, "paquetDeChipsMolles");
		GameRegistry.registerItem(paquetDeCigarettesEntame, "paquetDeCigarettesEntame");
		GameRegistry.registerItem(paracetoide7G,"paracetoide7G");
		GameRegistry.registerItem(pavesDeBetonInformes, "pavesDeBetonInformes");
		GameRegistry.registerItem(pavesDeBetonInformesCasses, "pavesDeBetonInformesCasses");
		GameRegistry.registerItem(peluresDePeau, "peluresDePeau");
		GameRegistry.registerItem(petitBeurresRances, "petiBeurresRances");
		GameRegistry.registerItem(petitMancheVibrant, "petitMancheVibrant");
		GameRegistry.registerItem(petitMancheVibrantEteint, "petitMancheVibrantEteint");
		GameRegistry.registerItem(petiteChaineHiFi, "petiteChaineHiFi");
		GameRegistry.registerItem(petiteChaineHiFiEnPanne, "petiteChaineHiFiEnPanne");
		GameRegistry.registerItem(pile, "pile");
		GameRegistry.registerItem(pileBroyee, "pileBroyee");
		GameRegistry.registerItem(pileDeFeuille, "pileDeFeuille");
		GameRegistry.registerItem(pimsPerime, "pimsPerime");
		GameRegistry.registerItem(piqureDeCalmant,"piqureDeCalmant");
		GameRegistry.registerItem(pistoletAEau,"pistoletAEau");
		GameRegistry.registerItem(pistoletAEauVide,"pistoletAEauVide");
		GameRegistry.registerItem(planchesTordue, "planchesTordue");
		GameRegistry.registerItem(plaqueDeBoisSolide,"plaqueDeBoisSolide");
		GameRegistry.registerItem(plaqueDeTole,"plaqueDeTole");
		GameRegistry.registerItem(platFaitMaisonDouteux,"platFaitMaisonDouteux");
		GameRegistry.registerItem(poigneeDeBonbons, "poigneeDeBonbons");
		GameRegistry.registerItem(poigneeDeVisEtEcrous, "poigneeDeVisEtEcrous");
		GameRegistry.registerItem(pointDAtelier,"pointDAtelier");
		GameRegistry.registerItem(pointDeChantier,"pointDeChantier");
		//GameRegistry.registerItem(pointeurLaserBrulant,"pointeurLaserBrulant");
		//GameRegistry.registerItem(pointeurLaserBrulantDecharge,"pointeurLaserBrulantDecharge");
		GameRegistry.registerItem(pomme,"pomme");
		GameRegistry.registerItem(pompeAJerrycanChargee,"pompeAJerrycanChargee");
		GameRegistry.registerItem(pompeAJerrycanDemontee,"pompeAJerrycanDemontee");
		GameRegistry.registerItem(pompeAJerrycanVide,"pompeAJerrycanVide");
		GameRegistry.registerItem(portiereDeVoiture,"portiereDeVoiture");
		GameRegistry.registerItem(portiereDeVoitureIncomplete,"portiereDeVoitureIncomplete");
		GameRegistry.registerItem(poudreCometeBrute,"poudreCometeBrute");
		GameRegistry.registerItem(poudreSuperFuzz,"poudreSuperFuzz");
		GameRegistry.registerItem(poutreRafistolee,"poutreRafistolee");
		GameRegistry.registerItem(produitCorrosif, "produitCorrosif");
		GameRegistry.registerItem(produitsPharmaceutiques, "produitsPharmaceutiques");
		GameRegistry.registerItem(pureeDeCharognardes, "pureeDeCharognardes");
		GameRegistry.registerItem(pureeDeCharognardesPoison, "pureeDeCharognardesPoison");
		GameRegistry.registerItem(radiusMarkII, "radiusMarkII");
		GameRegistry.registerItem(radiusMarkIIDechargee, "radiusMarkIIDechargee");
		GameRegistry.registerItem(radioK7, "radioK7");
		GameRegistry.registerItem(radioK7Eteint, "radioK7Eteint");
		GameRegistry.registerItem(rationDEau,"rationDEau");
		GameRegistry.registerItem(rationDEauPoison,"rationDEauPoison");
		GameRegistry.registerItem(refrigerateurDEtudiant, "refrigerateurDEtudiant");
		GameRegistry.registerItem(refrigerateurDEtudiantCasse, "refrigerateurDEtudiantCasse");
		GameRegistry.registerItem(revolverVide, "revolverVide");
		GameRegistry.registerItem(rockingChair, "rockingChair");
		GameRegistry.registerItem(rustine, "rustine");
		GameRegistry.registerItem(sacDeCiment,"sacDeCiment");
		GameRegistry.registerItem(sacPlastique,"sacPlastique");
		GameRegistry.registerItem(sacPlastiqueExplosif,"sacPlastiqueExplosif");
		GameRegistry.registerItem(sacSuperPratique,"sacSuperPratique");
		GameRegistry.registerItem(sacSupplementaire,"sacSupplementaire");
		GameRegistry.registerItem(sachetDHerbeFraiche,"sachetDHerbeFraiche");
		GameRegistry.registerItem(scieAMetaux,"scieAMetaux");
		GameRegistry.registerItem(scieAMetauxAbimee,"scieAMetauxAbimee");
		GameRegistry.registerItem(soucheDeBoisPourrie,"soucheDeBoisPourrie");
		GameRegistry.registerItem(sportElecCharge,"sportElecCharge");
		GameRegistry.registerItem(sportElecEteint,"sportElecChargeEteint");
		GameRegistry.registerItem(steakAppetissant, "steakAppetissant");
		GameRegistry.registerItem(steakDeSciure, "steakdeSciure");
		GameRegistry.registerItem(steroidesAnabolisants, "steroidesAnabolisants");
		GameRegistry.registerItem(steroidesAnabolisantsPoison, "steroidesAnabolisantsPoison");
		GameRegistry.registerItem(structuresMetalliques,"structuresMetalliques");
		GameRegistry.registerItem(substanceEpaisse,"substanceEpaisse");
		GameRegistry.registerItem(tableJarpen, "tableJarpen");
		GameRegistry.registerItem(tapisPersan, "tapisPersan");
		GameRegistry.registerItem(taserDAutoDefenseCharge, "taserDAutoDefenseCharge");
		GameRegistry.registerItem(taserDAutoDefenseEteint, "taserDAutoDefenseEteint");
		GameRegistry.registerItem(teddyNOurs, "teddyNOurs");
		GameRegistry.registerItem(teddyNOursMaudit, "teddyNOursMaudit");
		GameRegistry.registerItem(telephonePortable, "telephonePortable");
		GameRegistry.registerItem(telescope, "telescope");
		GameRegistry.registerItem(toileDeTente, "toileDeTente");
		GameRegistry.registerItem(tondeuseAGazon, "tondeuseAGazon");
		GameRegistry.registerItem(tondeuseAGazonCassee, "tondeuseAGazonCassee");
		GameRegistry.registerItem(tondeuseAGazonDemontee, "tondeuseAGazonDemontee");
		GameRegistry.registerItem(torche, "torche");
		GameRegistry.registerItem(torcheConsumee, "torcheConsumee");
		GameRegistry.registerItem(torcheConsumeeCassee, "torcheConsumeeCassee");
		GameRegistry.registerItem(tournevis, "tournevis");
		GameRegistry.registerItem(tournevisCasse, "tournevisCasse");
		GameRegistry.registerItem(toxine, "toxine");
		GameRegistry.registerItem(treteau, "treteau");
		GameRegistry.registerItem(tronconneuseChargee, "tronconneuseChargee");
		GameRegistry.registerItem(tronconneuseEteinte, "tronconneuseEteinte");
		GameRegistry.registerItem(tronconneuseIncomplete, "tronconneuseIncomplete");
		GameRegistry.registerItem(tubeDeCuivre, "tubeDeCuivre");
		GameRegistry.registerItem(tubeDeLancementFloush,"tubeDeLancementFloush");
		GameRegistry.registerItem(twinoides500Mg, "twinoides500Mg");
		GameRegistry.registerItem(uneEncyclopedie,"uneEncyclopedie");
		GameRegistry.registerItem(uneEtiquette, "uneEtiquette");
		GameRegistry.registerItem(uneLettreSansAdresse, "uneLettreSansAdresse");
		GameRegistry.registerItem(uniteCentrale, "uniteCentrale");
		GameRegistry.registerItem(uniteCentraleCassee, "uniteCentraleCassee");
		GameRegistry.registerItem(viandeHumaine, "viandeHumaine");
		GameRegistry.registerItem(viandeIndefinissable, "viandeIndefinissable");
		GameRegistry.registerItem(vieilleMachineALaver, "vieilleMachineALaver");
		GameRegistry.registerItem(vieilleMachineALaverCassee, "vieilleMachineALaverCassee");
		GameRegistry.registerItem(vieillePorte, "vieillePorte");
		GameRegistry.registerItem(vodkaMarinostov, "vodkaMarinostov");
		
		GameRegistry.registerItem(planCommun, "planCommun");
		GameRegistry.registerItem(planCommunHopital, "planCommunHopital");
		GameRegistry.registerItem(planInhabituel, "planInhabituel");
		GameRegistry.registerItem(planInhabituelBunker, "planInhabituelBunker");
		GameRegistry.registerItem(planInhabituelHopital, "planInhabituelHopital");
		GameRegistry.registerItem(planInhabituelHotel, "planInhabituelHotel");
		GameRegistry.registerItem(planRare, "planRare");
		GameRegistry.registerItem(planRareBunker, "planRareBunker");
		GameRegistry.registerItem(planRareHopital, "planRareHopital");
		GameRegistry.registerItem(planRareHotel, "planRareHotel");
		GameRegistry.registerItem(planTresRare, "planTresRare");
		GameRegistry.registerItem(planTresRareBunker, "planTresRareBunker");
		GameRegistry.registerItem(planTresRareHopital, "planTresRareHopital");
		GameRegistry.registerItem(planTresRareHotel, "planTresRareHotel");
		
		GameRegistry.registerItem(itemTest, "itemTest");
	}
	
	public static void itemRegisterDuringInit(){
		GameRegistry.registerItem(affaireDUnCitoyen, "affaireDUnCitoyen");
		GameRegistry.registerItem(appareilElectroniqueRepare, "appareilElectroniqueRepare");
		GameRegistry.registerItem(boiteDeJeu, "boiteDeJeu");
		GameRegistry.registerItem(boiteDejeuner, "boiteDejeuner");
		//GameRegistry.registerItem(boiteDeSchrodinger, "boiteDeSchrodinger");
		GameRegistry.registerItem(boiteEnMetalOuverte, "boiteEnMetalOuverte");
		GameRegistry.registerItem(caisseDeMaterielOuverte, "caisseDeMaterielOuverte");
		GameRegistry.registerItem(cartonDeMateriaux, "cartonDeMateriaux");
		GameRegistry.registerItem(coffreDArchitecte, "coffreDArchitecte");
		GameRegistry.registerItem(coffreDArchitecteOuvert, "coffreDArchitecteOuvert");
		GameRegistry.registerItem(doggyBag, "coggyBag");
		GameRegistry.registerItem(ecritAleatoire,"ecritAleatoire");
		GameRegistry.registerItem(grosCoffreFortEnMetalOuvert,"grosCoffreFortEnMetalOuvert");
		GameRegistry.registerItem(mecanismeDemonte,"mecanismeDemonte");
		GameRegistry.registerItem(meubleEnKitAssemble,"meubleEnKitAssemble");
		GameRegistry.registerItem(reserveDUnCitoyenAvise,"reserveDUnCitoyenAvise");
		GameRegistry.registerItem(sacocheUsee,"sacocheUsee");
		GameRegistry.registerItem(substanceAIdentifier,"substanceAIdentifier");
		GameRegistry.registerItem(uneEnveloppe,"uneEnveloppe");

		GameRegistry.registerItem(caisseDeNourritureOuverte, "caisseDeNourritureOuverte");
		GameRegistry.registerItem(coffreFortOuvert, "coffreFortOuvert");
		GameRegistry.registerItem(colisPostal,"colisPostal");
		GameRegistry.registerItem(grosColisPostal,"grosColisPostal");
		GameRegistry.registerItem(unColis, "unColis");
	}
}
